export const SFX_IDS = [
  'ui_click',
  'ui_confirm',
  'ui_cancel',
  'ui_tab',
  'ui_error',
  'title_start',
  'care_eat',
  'care_drink',
  'care_medicine',
  'care_toy',
  'care_happy',
  'level_up',
  'evolve',
  'hatch',
  'battle_windup',
  'battle_travel',
  'battle_impact',
  'battle_recover',
  'battle_guard',
  'battle_dodge',
  'battle_heal',
  'battle_flee',
  'battle_ko',
  'battle_win',
  'battle_lose',
  'jump',
  'land',
  'minigame_hit',
  'minigame_over',
  'collect',
  'market_buy',
  'item_use',
  'breed',
  'release',
  'mission_claim',
  'chat_dash',
  'chat_bite',
  'egg_notify',
  'notification_pop'
] as const

export type SfxId = (typeof SFX_IDS)[number]
