// Auto-generated by scripts/promote-creature-prototypes.mjs — do not edit by hand.
import type { CreatureSpecies } from './creatureCharacters'
import { CREATURE_FRAME_SIZE } from './creatureCharacters'

export type CreatureClipEntry = { frameSize: number; frames: number }

export const CREATURE_FRAME_MANIFEST = {
  "neutral": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  },
  "fire": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  },
  "grass": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  },
  "ground": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  },
  "electric": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  },
  "water": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  },
  "ice": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  },
  "dragon": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  },
  "dark": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  },
  "kmutnb": {
    "egg": {
      "move": {
        "frameSize": 192,
        "frames": 6
      },
      "hatch": {
        "frameSize": 192,
        "frames": 6
      }
    },
    "baby": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    },
    "adult": {
      "idle": {
        "frameSize": 192,
        "frames": 4
      },
      "move": {
        "frameSize": 192,
        "frames": 4
      },
      "hurt": {
        "frameSize": 192,
        "frames": 4
      },
      "bite": {
        "frameSize": 192,
        "frames": 4
      },
      "jump": {
        "frameSize": 192,
        "frames": 4
      }
    }
  }
} as const satisfies Record<
  CreatureSpecies,
  Record<string, Record<string, CreatureClipEntry>>
>

export function creatureFrameSize(
  species: CreatureSpecies,
  stage: string,
  clip: string
): number | undefined {
  return CREATURE_FRAME_MANIFEST[species]?.[stage]?.[clip]?.frameSize
}

export function creatureMaxFrameSize(species: CreatureSpecies, stage: string): number {
  const clips = CREATURE_FRAME_MANIFEST[species]?.[stage]
  if (!clips) return CREATURE_FRAME_SIZE
  const sizes = Object.values(clips).map((entry) => entry.frameSize)
  return sizes.length > 0 ? Math.max(...sizes) : CREATURE_FRAME_SIZE
}
